name: Building
on:  
  push:
  pull_request:
 
jobs:
 building-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B. C , D]
 
    steps:
    - uses: actions/checkout@v3
    - name: building1
      run: echo "create build1"
 
 building-2:
    runs-on: ubuntu-latest
    needs: building-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B]
 
    timeout-minutes: 58
    steps:
    - uses: actions/checkout@v3
    - name: Oke-Build1
      continue-on-error: true
      run: |
        echo 'hello'
        sleep 60
        echo 'done'
